### ISSUE TITLE
UploadSlaveByFilename 这个什么意思

### ISSUE THREAD

**Issue by Icedroid** [weilaihui/fdfs_client#1]
UploadSlaveByFilename 这个是上传到fastdfs的另一个节点？
代码一行注释都没有，一个说明都没，如何让人使用呢？

**Comment by Icedroid** [comment]
client_test.go:151: DownloadToFile error [-] Error: Storage response length is not match, expect: 512, actual: 512
这个不支持断点续传吗？就是downloadSize先传递一个小于文件大小的值。后面再用offect加上偏移来分次下载。

**Comment by weilaihui** [comment]
UploadSlaveByFilename 是上传一个跟主文件相关联的文件，他们的file_id跟主文件是类似的，唯一不同是后缀，举个常见例子，用来存储图片原文件和它的压缩文件，那么取得时候可以直接用{file_id}_480.jpg这样的形式来取。

**Comment by Icedroid** [comment]
@weilaihui 谢谢呀
