### ISSUE TITLE
github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"

### ISSUE THREAD

**Issue by 39499740** [weilaihui/fdfs_client#14]
github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"

Sirupsen/logrus   现在被转移到小写的sirupsen/logrus下了
你这边能更新一下么？要不然用go mod的时候会冲突……

**Comment by weilaihui** [comment]
好的哦，下午就换发自我的华为手机-------- 原始邮件 --------主题：[weilaihui/fdfs_client] github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus" (#14)发件人：39499740 收件人：weilaihui/fdfs_client 抄送：Subscribed github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"

Sirupsen/logrus   现在被转移到小写的sirupsen/logrus下了

你这边能更新一下么？要不然用go mod的时候会冲突……
