### ISSUE TITLE
time="2015-01-29T09:46:12+08:00" level=warning msg="write tcp 192.168.1.63:23000: broken pipe"

### ISSUE THREAD

**Issue by Icedroid** [weilaihui/fdfs_client#2]
偶尔会出现这个错误，而我用PHP fastdfs就不会的，是什么原因呢？

**Comment by weilaihui** [comment]
请先确保192.168.1.63的23000端口打开的，fdfs_client的连接池并没有检查连接是否可用即返回了连接，有可能是出现错误中断了该连接句柄。

**Comment by Icedroid** [comment]
那能不能加个检查可用才返回连接呢？我跑你目录下的client_test是没问题的，但线上的上传测试就出现这个错误。

**Comment by weilaihui** [comment]
麻烦执行下 fdfs_monitor /etc/fdfs/client.conf 看看有哪些运行的storage呢

**Comment by weilaihui** [comment]
我们实际环境中使用几乎从没有出现过连接不可用的

**Comment by Icedroid** [comment]
[root@192 data]# /usr/local/bin/fdfs_monitor /etc/fdfs/client.conf 
[2015-01-29 10:45:00] DEBUG - file: fdfs_shared_func.c, line: 519, g_storage_id_count: 2
[2015-01-29 10:45:00] DEBUG - 100001  group1  192.168.1.63
[2015-01-29 10:45:00] DEBUG - 100002  group2  192.168.1.60
[2015-01-29 10:45:00] DEBUG - base_path=/home/fastdfs_storage, connect_timeout=30, network_timeout=60, tracker_server_count=1, anti_steal_token=0, anti_steal_secret_key length=0, use_connection_pool=0, g_connection_pool_max_idle_time=3600s, use_storage_id=1, storage server id count: 2

server_count=1, server_index=0

tracker server is 192.168.1.63:22122

group count: 2

Group 1:
group name = group1
disk total space = 112640 MB
disk free space = 77638 MB
trunk free space = 0 MB
storage server count = 1
active server count = 1
storage server port = 23000
storage HTTP port = 8888
store path count = 1
subdir count per path = 256
current write server index = 0
current trunk file id = 0

	Storage 1:
		id = 100001
		ip_addr = 192.168.1.63 (192.168.1.63)  ACTIVE

**Comment by weilaihui** [comment]
服务端storage日志有报错信息没有呢

**Comment by Icedroid** [comment]
php client地址...这个是服务端调用 的
storage日志有报错：
[2015-01-29 09:44:12] ERROR - file: storage_nio.c, line: 227, client ip: 192.168.1.60, recv timeout, recv offset: 0, expect length: 0

**Comment by Icedroid** [comment]
你们真的有在线上使用过这个client吗？我又遇到这个错误了。

**Comment by weilaihui** [comment]
增加了下载文件的压测，你可以看看

**Comment by Icedroid** [comment]
@weilaihui 这个是上传文件时出现的喔，用file buffer上传的。

**Comment by weilaihui** [comment]
我重新写了上传文件压测没有碰到过问题

**Comment by Icedroid** [comment]
上传完全没法用，我只能撤 下来了，你可以并发压一下，真的超多上传错误：
time="2015-02-06T17:05:30+08:00" level=warning msg="write tcp 10.10.8.191:23000: broken pipe"

**Comment by weilaihui** [comment]
你可以跟下错误，帮忙解决下这个bug吧

**Comment by Icedroid** [comment]
@weilaihui 我没找到你这句提示是在哪里打印的，这种错误应该返回给使用者，不要直接打印吧，你用ab并发压一下应该很快发现问题的。

**Comment by weilaihui** [comment]
错误是返回了的，应该是建立连接时的错误，你看代码，错误我没有处理，都是直接返回的。我回头单独压下

**Comment by weilaihui** [comment]
我压了100W也没看到报错呢，你看看netstat -anp  |  grep 22122 和 netstat -anp  |  grep 23000正常不呢

**Comment by benbuzhidao** [comment]
storage连接池缺失有问题，服务起来后，你重启掉fdfs的storage 再上传测试就会有问题。

**Comment by benbuzhidao** [comment]
我简单修复了下，增加连接可用校验
