### ISSUE TITLE
DownloadToFile的offect和size参数只能是0和0吗？

### ISSUE THREAD

**Issue by Icedroid** [weilaihui/fdfs_client#3]
我传offect=0,size=512就出现下面的错误：
client_test.go:151: DownloadToFile error [-] Error: Storage response length is not match, expect: 512, actual: 512
这个不支持断点续传吗？就是downloadSize先传递一个小于文件大小的值。后面再用offect加上偏移来分次下载。

**Comment by weilaihui** [comment]
你重新更新下源码试试

**Comment by Icedroid** [comment]
It is fixed. Thank you.
